version: 0.2

env:
  variables:
    FRAMEWORK_FULL_VERSION: '1.3.0'
    FRAMEWORK_SHORT_VERSION: '1.3'
    AWS_DEFAULT_REGION: 'us-west-2'
    ECR_REPO: 'sagemaker-mxnet'
    GITHUB_REPO: 'sagemaker-mxnet-container'
    GPU_INSTANCE_TYPE: 'p2.xlarge'


phases:
  pre_build:
    commands:
      - start-dockerd

      - ACCOUNT=$(aws sts get-caller-identity --query 'Account' --output text)
      - BUILD_DIR="docker/$FRAMEWORK_FULL_VERSION/final"

      # keep ssh connection alive when communicating with remote ec2 server during integ test
      # largest connection idle time allowed: 10 seconds * 360 attempts = 60 minutes
      - echo '  ServerAliveInterval 10' >> ~/.ssh/config
      - echo '  ServerAliveCountMax 360' >> ~/.ssh/config

  build:
    commands:
      # prepare the release (update versions, changelog etc.)
      - git-release --prepare

      - tox -e flake8

      # run unit tests
      - tox -e py27,py36 test/unit

      # Create pip archive (tar_name will be something like sagemaker_mxnet_container-2.0.0.tar.gz)
      - python3 setup.py sdist
      - tar_name=$(ls dist)
      - cp dist/$tar_name $BUILD_DIR

      # build images
      - python3 scripts/build_all.py --version $FRAMEWORK_FULL_VERSION --account $ACCOUNT --repo $ECR_REPO

      # push docker images to ECR
      - python3 scripts/publish_all.py --version $FRAMEWORK_FULL_VERSION --account $ACCOUNT --repo $ECR_REPO

      # run cpu integration tests
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/local --py-version 3 --processor cpu --framework-version $FRAMEWORK_FULL_VERSION --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/local --py-version 2 --processor cpu --framework-version $FRAMEWORK_FULL_VERSION --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO

      # launch remote gpu instance
      - create-key-pair
      - launch-ec2-instance --instance-type $GPU_INSTANCE_TYPE --ami-name dlami-ubuntu

      # TODO: make sure both Python versions are run
      # TODO: fix docker base name
      # run gpu integration tests
      - cmd="IGNORE_COVERAGE=- tox -e py36 -- test/integration/local --region $AWS_DEFAULT_REGION --docker-base-name $PREPROD_IMAGE --framework-version $FRAMEWORK_VERSION --processor gpu"
      # - remote-test --github-repo $GITHUB_REPO --test-cmd "$cmd"

      # run cpu sagemaker tests
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --py-version 3 --processor cpu --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_FULL_VERSION
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --py-version 2 --processor cpu --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_FULL_VERSION

      # run gpu sagemaker tests
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --py-version 3 --processor gpu --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_FULL_VERSION
      - IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker --py-version 2 --processor gpu --region $AWS_DEFAULT_REGION --docker-base-name $ECR_REPO --aws-id $ACCOUNT --framework-version $FRAMEWORK_FULL_VERSION

      # TODO: make sure all tests are run
      # write deployment details to file
      - |
        echo '[{
          "repository": "'$ECR_REPO'",
          "tags": [{
            "source": "'$FRAMEWORK_FULL_VERSION'-cpu-py2",
            "dest": ["'$FRAMEWORK_FULL_VERSION'-cpu-py2", "'$FRAMEWORK_SHORT_VERSION'-cpu-py2", "'$FRAMEWORK_FULL_VERSION'-cpu-py2-'${CODEBUILD_BUILD_ID#*:}'"]
          },{
            "source": "'$FRAMEWORK_FULL_VERSION'-gpu-py2",
            "dest": ["'$FRAMEWORK_FULL_VERSION'-gpu-py2", "'$FRAMEWORK_SHORT_VERSION'-gpu-py2", "'$FRAMEWORK_FULL_VERSION'-gpu-py2-'${CODEBUILD_BUILD_ID#*:}'"]
          },{
            "source": "'$FRAMEWORK_FULL_VERSION'-cpu-py3",
            "dest": ["'$FRAMEWORK_FULL_VERSION'-cpu-py3", "'$FRAMEWORK_SHORT_VERSION'-cpu-py3", "'$FRAMEWORK_FULL_VERSION'-cpu-py3-'${CODEBUILD_BUILD_ID#*:}'"]
          },{
            "source": "'$FRAMEWORK_FULL_VERSION'-gpu-py3",
            "dest": ["'$FRAMEWORK_FULL_VERSION'-gpu-py3", "'$FRAMEWORK_SHORT_VERSION'-gpu-py3", "'$FRAMEWORK_FULL_VERSION'-gpu-py3-'${CODEBUILD_BUILD_ID#*:}'"]
          }]
        }, {
          "test": [
            "IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n auto --py-version 3 --processor cpu --region {region} --docker-base-name '$ECR_REPO' --aws-id 520713654638 --framework-version '$FRAMEWORK_FULL_VERSION'"
            "IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n auto --py-version 3 --processor gpu --region {region} --docker-base-name '$ECR_REPO' --aws-id 520713654638 --framework-version '$FRAMEWORK_FULL_VERSION'"
            "IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n auto --py-version 2 --processor cpu --region {region} --docker-base-name '$ECR_REPO' --aws-id 520713654638 --framework-version '$FRAMEWORK_FULL_VERSION'"
            "IGNORE_COVERAGE=- tox -e py36 -- test/integration/sagemaker -n auto --py-version 2 --processor gpu --region {region} --docker-base-name '$ECR_REPO' --aws-id 520713654638 --framework-version '$FRAMEWORK_FULL_VERSION'"
          ]
        }]' > deployments.json

      # publish the release to github
      - git-release --publish

    finally:
      # shut down remote gpu instance
      - cleanup-gpu-instances
      - cleanup-key-pairs

artifacts:
  files:
    - deployments.json
name: ARTIFACT_1
